### ISSUE TITLE
Troubleshooting Geometry Nodes Script: Issues with set_position and Vertex Selection

### ISSUE THREAD

**Issue by pterusgithub** [al1brn/geonodes#9]
Hi,

Here’s the script I’m testing at the moment:
```python
with geon.GeoNodes(nameofnode_group):
    ligne = geon.Mesh.Line(end_location=(0.5, 0, 0), count=1)
    ligne.points.extrude(offset=(0, 1, 0))
    ligne.points[ligne.top_].extrude(offset=(1, 0, 0))
    ligne.points[ligne.top_].extrude(offset=(0, -1, 0))
    ligne.points[ligne.top_].extrude(offset=(0, 0, 0))
    ligne.points[ligne.top_].set_position(position=(0, 0, 0))  # Doesn't work. Why?
    geo = ligne.merge_by_distance(distance=0.1)
    geo.out()
```
I’m experimenting with selecting specific vertices. The extrude method works perfectly, but I’m running into issues with set_position. I can’t quite figure out what’s causing the error.

Here’s the traceback:
```shell
Tree 'ligne_test' built: 11 nodes, 13 links in 0.0 s
Error: Python: Traceback (most recent call last):
  File "/2024-12-06_geonodes-001.py", line 436, in <module>
  File "/usr/local/blender-4.3.0-linux-x64/4.3/scripts/modules/geonodes/core/geometryclass.py", line 241, in set_position
    return self._jump(node._out)
                      ^^^^^^^^^
  File "/usr/local/blender-4.3.0-linux-x64/4.3/scripts/modules/geonodes/core/socketclass.py", line 332, in __getattr__
    raise AttributeError(f"Class {type(self).__name__} as no property named '{name}'")
AttributeError: Class Geometry has no property named '_out'. Did you mean: 'out'?
```
Interestingly, when I remove the selection (`ligne.points[ligne.top_]`), the command `ligne.set_position(position=(0, 0, 0))` works fine.

Any idea what’s causing this issue? Thanks in advance!

**Comment by al1brn** [comment]
Bonjour,

Yet another bug on my side. It is corrected.

your code is correct but you can also use the property syntax (this one was not bugged):

``` python
    ligne.points[ligne.top_].position = (0, 0, 0)
```

Note that you can also use the offset property if required

``` python
    ligne.points[ligne.top_].offset = (1, 0, 0)
```

If you are blocked, waiting for the correction, you have the possibility to use nd library to create directly the bugged method:

``` python
    ligne = geon.nd.set_position(geometry=ligne, selection=ligne.top_, position=(0, 0, 0))
```
btw, I'm still working in making ShaderNodes available in autocompletion. I really don't understand why it doesn't work.

BR
